# notifier.py - EML 草稿產生器 (零密碼 + 自動帶附件 + 跨平台 100% 成功)
import os
import sys
import webbrowser
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import config

def generate_html_summary(breaks_df):
    """生成 HTML 郵件內文，大額 Break 自動標示深紅"""
    total_breaks = len(breaks_df)
    total_diff = breaks_df['Difference'].abs().sum()
    
    large_breaks = breaks_df[breaks_df['Difference'].abs() >= config.LARGE_BREAK_THRESHOLD]
    has_large_break = len(large_breaks) > 0
    
    status_header = "<h2 style='color: #C00000;'>🚨 [URGENT] Large Discrepancy Alert Detected</h2>" if has_large_break else "<h2 style='color: #1F4E78;'> Daily Reconciliation Summary Report</h2>"

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; padding: 10px;">
        {status_header}
        <p>Today's automated reconciliation run has completed with the following stats:</p>
        <ul>
            <li><b>Total Breaks:</b> {total_breaks}</li>
            <li><b>Total Discrepancy Amount:</b> ${total_diff:,.2f}</li>
            <li><b>Large Breaks (>= ${config.LARGE_BREAK_THRESHOLD:,.0f}):</b> <span style="color: red; font-weight: bold;">{len(large_breaks)}</span></li>
        </ul>
        <h3>Break Breakdown Table:</h3>
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
            <tr style="background-color: #1F4E78; color: white;">
                <th>Trade ID</th>
                <th>Product</th>
                <th>Internal Notional</th>
                <th>External Notional</th>
                <th>Difference</th>
                <th>Break Type</th>
            </tr>
    """
    
    for _, row in breaks_df.iterrows():
        bg_color = "#FFFFFF"
        if abs(row['Difference']) >= config.LARGE_BREAK_THRESHOLD:
            bg_color = "#FF9999"
        elif row['Break_Type'] == 'NOTIONAL_MISMATCH':
            bg_color = "#FFC7CE"
        elif row['Break_Type'] == 'MISSING_ON_BROKER':
            bg_color = "#FFEB9C"
        elif row['Break_Type'] == 'MISSING_IN_HOUSE':
            bg_color = "#FCE4D6"
            
        html += f"""
            <tr style="background-color: {bg_color};">
                <td>{row['Trade_ID']}</td>
                <td>{str(row['Product'])}</td>
                <td>${row['Internal_Notional']:,.2f}</td>
                <td>${row['External_Notional']:,.2f}</td>
                <td>${row['Difference']:,.2f}</td>
                <td><b>{row['Break_Type']}</b></td>
            </tr>
        """
        
    html += """
        </table>
        <p style="font-size: 11px; color: gray; margin-top: 20px;">This is an automated system audit alert. Generated by Reconciliation Pipeline Engine.</p>
    </body>
    </html>
    """
    return html, has_large_break

def send_reco_email(breaks_df, attachment_path, dry_run=False):
    """生成包含附件與 HTML 內文的 .eml 郵件草稿檔案，並用 Windows 自動開啟"""
    html_content, has_large_break = generate_html_summary(breaks_df)
    
    subject_prefix = "[URGENT ALERT]" if has_large_break else "[REPORT]"
    subject = f"{subject_prefix} Daily Trade Reconciliation - {len(breaks_df)} Breaks"
    
    # 建立完整的 MIME 郵件結構
    msg = MIMEMultipart()
    msg['To'] = ", ".join(config.RECIPIENTS)
    msg['Subject'] = subject
    msg['X-Unsent'] = '1'  # 關鍵標記：告訴 Outlook/Mail 這是一份「未發送草稿」
    
    # 附加 HTML 內文
    msg.attach(MIMEText(html_content, 'html'))
    
    # 附加 Excel 實體檔案
    if os.path.exists(attachment_path):
        with open(attachment_path, "rb") as f:
            part = MIMEApplication(f.read(), Name=os.path.basename(attachment_path))
            part['Content-Disposition'] = f'attachment; filename="{os.path.basename(attachment_path)}"'
            msg.attach(part)

    # 存成 .eml 實體檔案
    eml_file = "Daily_Reconciliation_Draft.eml"
    with open(eml_file, "wb") as f:
        f.write(msg.as_bytes())
        
    abs_eml_path = os.path.abspath(eml_file)
    
    # 喚醒系統預設郵件軟體開啟該草稿
    os.system(f'start "" "{abs_eml_path}"')
    
    print("\n==================================================")
    print(" [EML DRAFT GENERATOR] 郵件草稿（含附件）已成功生成！")
    print(f" 草稿檔位置: {abs_eml_path}")
    print("==================================================")
    return True